### ISSUE TITLE
Type instability in `vtk_save`?

### ISSUE THREAD

**Issue by jlchan** [jipolanco/WriteVTK.jl#116]
Thanks for maintaining this package! 

I ran into a type instability in `vtk_save` recently when working with an unstructured grid data type. Here is a MWE:
```julia
using WriteVTK
cells = [MeshCell(VTKCellTypes.VTK_LAGRANGE_TRIANGLE, [1, 2, 3])]
vtkfile = vtk_grid("test", [-1, -1, 1], [-1, 1, -1], cells)
@code_warntype vtk_save(vtkfile)
```
The output of `@code_warntype` is 
<img width="1090" alt="Screen Shot 2023-02-14 at 3 23 05 PM" src="https://user-images.githubusercontent.com/1156048/218866135-04c1f88d-d928-4a52-88c9-7c0bd9c4371b.png">

Any idea if this can be made type stable?

**Comment by jipolanco** [comment]
I'm not really sure why assertions sometimes are flagged as non-inferred by `@code_warntype`, but I believe this is completely harmless and doesn't impact performance. But I can provide a workaround for this if it helps.

In any case, I really think this is not what is causing the type instability that you're seeing in jlchan/StartUpDG.jl#87, since the return type of `vtk_save` is correctly inferred.
