### ISSUE TITLE
vtk_cell_data() writes data out incorrectly

### ISSUE THREAD

**Issue by abahm** [jipolanco/WriteVTK.jl#31]
Using the following code to write out the same data A (a spherical dataset), vtk_cell_data() produces  something garbled when viewed by Paraview in volume rendering mode, whereas vtk_write_array() writes it correctly.

```
# julia code to demonstrate problem
using WriteVTK

Npoints = 101
Ncells = Npoints - 1
A = zeros(Ncells, Ncells, Ncells)
c = Ncells/2.0
for i in 1:Ncells, j in 1:Ncells, k in 1:Ncells
    A[i,j,k] = (i-c)^2 + (j-c)^2 + (k-c)^2
end

vtk_write_array("write_good_vti_file", A, "sphere")

vtk = vtk_grid("write_bad_vti_file", Npoints, Npoints, Npoints)
vtk_cell_data(vtk, A, "sphere")
vtk_save(vtk)
```

**Comment by jipolanco** [comment]
In your example, the only difference between using `vtk_write_array` and `vtk_cell_data` is that the first writes the array `A` as point data, and the second as cell data. The call to `vtk_write_array` in the example is exactly equivalent to:

```julia
# Here Ncells is actually the number of points!
vtk = vtk_grid("write_good_vti_file", Ncells, Ncells, Ncells)
vtk_point_data(vtk, A, "sphere")
vtk_save(vtk)
```

Your issue seems to be related to the way volume rendering works in Paraview. I've not really used volume rendering myself, but after opening both files I'd say that it works better when the input is point data instead of cell data. You can also see this by opening the generated `write_bad_vti_file.vti` in Paraview and then applying the "Cell Data to Point Data" filter. The resulting point data renders correctly, just like the data in `write_good_vti_file.vti`.

**Comment by abahm** [comment]
Thank you very much for your reply!   I will continue forward using
vtk_write_array and simply rescale it in Paraview.   Cheers, Alan
