### ISSUE TITLE
PVTK and rectilinear grids

### ISSUE THREAD

**Issue by corentin-dev** [jipolanco/WriteVTK.jl#96]
Rectilinear grids are lacking "Points" and find_element fails on it.

If x, y and z are simple vectors, pvtk_grid will show the following error.
```julia
pvtkfile = pvtk_grid("simulation", x, y, z; part = 1, nparts = 1)
ERROR: MethodError: no method matching find_element(::Nothing, ::String)
Closest candidates are:
  find_element(::LightXML.XMLElement, ::AbstractString) at ~/.julia/packages/LightXML/g6rbQ/src/nodes.jl:279
Stacktrace:
 [1] _init_pvtk!(pvtk::WriteVTK.PVTKFile)
   @ WriteVTK ~/.julia/packages/WriteVTK/lPORE/src/gridtypes/pvtk_grid.jl:121
 [2] pvtk_grid(::String, ::Vector{Float64}, ::Vararg{Any}; part::Int64, nparts::Int64, ismain::Bool, ghost_level::Int64, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ WriteVTK ~/.julia/packages/WriteVTK/lPORE/src/gridtypes/pvtk_grid.jl:53
 [3] top-level scope
   @ REPL[107]:1
 [4] top-level scope
   @ ~/.julia/packages/CUDA/sCev8/src/initialization.jl:52
```
It works as intended for StructuredGrid.

**Comment by jipolanco** [comment]
Hi, support for PVTK files is quite recent, and as mentioned [in the docs](https://jipolanco.github.io/WriteVTK.jl/dev/metadata/parallel/), only unstructured grids have been tested for now (I'm happy to know that structured grids work as well!).

Adding support for rectilinear grids should be quite easy. I can take a look at this next week, or otherwise I'm happy to take any PRs.

**Comment by corentin-dev** [comment]
Of course, thank you a lot for all the good work you put in this package by the way!

**Comment by corentin-dev** [comment]
I'll continue in the other issue, as all the work mentioned is already there. I started the work here:
https://github.com/corentin-dev/WriteVTK.jl/commit/49259fa562781e3d0e42256bdbc1056d2523b306
